export const products = [
    { id: 1, name: 'Item 1', price: '₹100.0', sameDayShipping: true },
    { id: 2, name: 'Item 2', price: '₹10.0', sameDayShipping: true },
    { id: 3, name: 'Item 3', price: '₹130.0', sameDayShipping: false },
    { id: 4, name: 'Item 4', price: '₹230.0', sameDayShipping: false },
    { id: 5, name: 'Item 5', price: '₹230.0', sameDayShipping: false },
    { id: 6, name: 'Item 6', price: '₹230.0', sameDayShipping: false },
    { id: 7, name: 'Item 7', price: '₹230.0', sameDayShipping: false },
    { id: 8, name: 'Item 8', price: '₹230.0', sameDayShipping: false },
    { id: 1, name: 'Item 1', price: '₹100.0', sameDayShipping: true },
    { id: 2, name: 'Item 2', price: '₹10.0', sameDayShipping: true },
    { id: 3, name: 'Item 3', price: '₹130.0', sameDayShipping: false },
    { id: 4, name: 'Item 4', price: '₹230.0', sameDayShipping: false },
    { id: 5, name: 'Item 5', price: '₹230.0', sameDayShipping: false },
    { id: 6, name: 'Item 6', price: '₹230.0', sameDayShipping: false },
    { id: 7, name: 'Item 7', price: '₹230.0', sameDayShipping: false },
    { id: 8, name: 'Item 8', price: '₹230.0', sameDayShipping: false },
    { id: 1, name: 'Item 1', price: '₹100.0', sameDayShipping: true },
    { id: 2, name: 'Item 2', price: '₹10.0', sameDayShipping: true },
    { id: 3, name: 'Item 3', price: '₹130.0', sameDayShipping: false },
    { id: 4, name: 'Item 4', price: '₹230.0', sameDayShipping: false },
    { id: 5, name: 'Item 5', price: '₹230.0', sameDayShipping: false },
    { id: 6, name: 'Item 6', price: '₹230.0', sameDayShipping: false },
    { id: 7, name: 'Item 7', price: '₹230.0', sameDayShipping: false },
    { id: 8, name: 'Item 8', price: '₹230.0', sameDayShipping: false },
];